/**
 * MovieReviews Component
 *
 * Displays movie reviews with AI-powered sentiment analysis.
 * Features:
 * - Parses review strings into structured author/content objects
 * - AI sentiment analysis integration using Gemini API
 * - ReactMarkdown rendering with HTML support for review content
 * - Scrollable review container with hover effects
 * - Interactive thumb up/down buttons for user feedback
 * - Review count display and loading state handling
 * - Gradient styling with card layout and borders
 *
 * Used in movie detail pages to showcase user reviews and AI insights.
 */

import { FaUserCircle } from "react-icons/fa";
import {
  SparklesIcon,
  HandThumbUpIcon,
  HandThumbDownIcon,
  InformationCircleIcon,
} from "@heroicons/react/24/solid";
import ReactMarkdown from "react-markdown";
import rehypeRaw from "rehype-raw"; // Import the plugin
import { useState } from "react";

export default function MovieReviews({ movie, sentiment }) {
  const [showTooltip, setShowTooltip] = useState(false);

  if (!movie?.reviews) {
    return <p className="text-gray-500 italic">No reviews available.</p>;
  }

  // Separate author name from review content, returning an object
  const parseReview = (review) => {
    const [firstLine, ...rest] = review.split("\n"); // Split first line assuming its the name
    return {
      // Return an object with author and content properties
      author: firstLine.trim(),
      content: rest.join("\n").trim(),
    };
  };

  // Processes movie reviews string into an array of structured objects
  const splitReviews = movie.reviews
    .split(/Author:\s*/g)
    .filter(Boolean)
    .map((review) => parseReview(review));

  return (
    <div className="bg-gradient-to-b from-slate-800/30 to-transparent shadow-md shadow-blue-400/50 border border-blue-100/50 rounded-lg">
      <div className="p-6 border-b border-slate-700/50">
        <h2 className="text-2xl font-semibold text-white">Reviews</h2>
        <p className="text-slate-400 text-sm">
          {splitReviews.length}{" "}
          {splitReviews.length === 1 ? "review" : "reviews"}
        </p>
        {sentiment && (
          <div className="mt-4 p-4 bg-gradient-to-b from-blue-600/20 to-transparent rounded-xl">
            <div className="flex items-center justify-between">
              <h3 className="text-white font-normal tracking-normal text-2xl pt-2">
                <SparklesIcon className="w-5 h-5 inline mr-1 text-white mb-2" />
                Smart Review
              </h3>

              <div className="relative">
                <button
                  onMouseEnter={() => setShowTooltip(true)}
                  onMouseLeave={() => setShowTooltip(false)}
                  className="text-slate-400 hover:text-white transition-colors"
                  aria-label="Learn more about AI summary"
                >
                  <InformationCircleIcon className="w-8 h-8" />
                </button>

                {showTooltip && (
                  <div className="absolute right-0 top-8 w-80 bg-slate-900 border border-slate-600 rounded-lg p-4 shadow-xl z-10">
                    <h4 className="text-white font-medium mb-2">
                      About this AI Summary
                    </h4>
                    <div className="text-slate-300 text-sm space-y-2">
                      <p>
                        <strong>Generated by:</strong> Google's Gemini AI
                      </p>
                      <p>
                        <strong>Source data:</strong> User reviews from The
                        Movie Database (TMDb)
                      </p>
                      <p>
                        <strong>AI Instructions:</strong> Analyze sentiment and
                        provide a plain-text summary focusing on overall
                        sentiment and collective opinions without individual
                        review breakdown
                      </p>
                      <p>
                        <strong>Purpose:</strong> Provides general sentiment
                        analysis of collective user opinions
                      </p>
                      <p className="text-yellow-400 text-xs">
                        ⚠️ AI outputs may reflect bias in source data and are
                        not a substitute for reading full reviews
                      </p>
                    </div>
                  </div>
                )}
              </div>
            </div>

            <p className="text-sm font-light text-cyan-400/80 border-b border-blue-500/20 pb-4 mb-2">
              Powered by Gemini AI • Based on user reviews
            </p>
            <p className="text-slate-300 font-light text-md">{sentiment}</p>
          </div>
        )}
      </div>

      <div className="max-h-[600px] overflow-y-auto">
        {splitReviews.map((review, idx) => (
          <div
            key={idx}
            className="p-6 border-b border-slate-700/20 hover:bg-slate-800/30 transition-colors"
          >
            <div className="flex items-start gap-4">
              <FaUserCircle className="w-10 h-10 text-blue-400 flex-shrink-0" />

              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <h3 className="text-white font-medium">{review.author}</h3>
                </div>

                <div className="text-white mb-4 tracking-wide font-light">
                  <ReactMarkdown
                    rehypePlugins={[rehypeRaw]}
                    components={{
                      p: ({ node, ...props }) => (
                        <p {...props} className="text-sm leading-relaxed" />
                      ),
                    }}
                  >
                    {review.content}
                  </ReactMarkdown>
                </div>

                <div className="flex items-center gap-4">
                  <button className="flex items-center gap-1 text-slate-400 hover:text-blue-400">
                    <HandThumbUpIcon className="w-4 h-4" />
                  </button>
                  <button className="flex items-center gap-1 text-slate-400 hover:text-red-400">
                    <HandThumbDownIcon className="w-4 h-4" />
                  </button>
                </div>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
